import { StyleSheet } from 'react-native';

export const cameraFillStyle = StyleSheet.absoluteFill;

const styles = StyleSheet.create({
    flex: { flex: 1 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },

    permissionBox: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    permEyebrow: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.8,
        marginBottom: 14,
    },
    permTitle: { fontSize: 22, fontWeight: '800', marginBottom: 12, textAlign: 'center' },
    permSub: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 32 },
    permBtn: {
        width: '100%',
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: '#D96C4A',
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 18,
        shadowOpacity: 0.28,
        elevation: 5,
    },
    permBtnText: {
        color: '#FFF',
        fontWeight: '700',
        fontSize: 17,
        letterSpacing: 0.4,
    },
    cancelBtn: {
        width: '100%',
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        borderWidth: 1,
    },
    cancelBtnText: { fontWeight: '600', fontSize: 15 },
    headerBackButton: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
    },

    camTopBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    camOverlayBtn: {
        backgroundColor: 'rgba(0,0,0,0.45)',
        paddingHorizontal: 16,
        paddingVertical: 9,
        borderRadius: 22,
    },
    camBtnTxt: { color: '#FFF', fontWeight: '600', fontSize: 14 },
    camLabel: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 2.4,
    },
    camGuide: {
        position: 'absolute',
        top: '20%',
        left: '8%',
        right: '8%',
        bottom: '20%',
    },
    camGuideCorner: {
        position: 'absolute',
        width: 24,
        height: 24,
        borderColor: 'rgba(255,255,255,0.55)',
    },
    camGuideCornerTL: { top: 0, left: 0, borderTopWidth: 2, borderLeftWidth: 2 },
    camGuideCornerTR: { top: 0, right: 0, borderTopWidth: 2, borderRightWidth: 2 },
    camGuideCornerBL: { bottom: 0, left: 0, borderBottomWidth: 2, borderLeftWidth: 2 },
    camGuideCornerBR: { bottom: 0, right: 0, borderBottomWidth: 2, borderRightWidth: 2 },
    shutterRow: {
        position: 'absolute',
        bottom: 52,
        left: 0,
        right: 0,
        alignItems: 'center',
    },
    shutterRing: {
        width: 84,
        height: 84,
        borderRadius: 42,
        borderWidth: 4,
        borderColor: 'rgba(255,255,255,0.75)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    shutterBtn: {
        width: 68,
        height: 68,
        borderRadius: 34,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    camHint: { color: 'rgba(255,255,255,0.6)', fontSize: 13, fontWeight: '500' },

    previewContent: {
        paddingTop: 16,
        paddingBottom: 140,
    },
    previewCard: {
        marginHorizontal: 16,
        borderRadius: 28,
        borderWidth: 1,
        overflow: 'hidden',
        shadowColor: '#120B09',
        shadowOffset: { width: 0, height: 12 },
        shadowRadius: 26,
        elevation: 4,
    },
    previewFrame: {
        height: 360,
        backgroundColor: '#1E1715',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    previewImg: {
        width: '100%',
        height: '100%',
    },
    previewShade: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(35, 20, 17, 0.14)',
    },
    capturedBadge: {
        position: 'absolute',
        top: 16,
        right: 16,
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 20,
    },
    capturedBadgeText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 1.5,
    },
    previewFooter: {
        paddingHorizontal: 18,
        paddingVertical: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 14,
    },
    previewCopy: {
        flex: 1,
        gap: 6,
    },
    previewTitle: {
        fontSize: 21,
        fontWeight: '800',
    },
    previewSub: {
        fontSize: 14,
        lineHeight: 20,
    },
    rotateButton: {
        minWidth: 96,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 18,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rotateButtonText: {
        fontSize: 14,
        fontWeight: '800',
        letterSpacing: 0.2,
    },
    infoCard: {
        marginTop: 16,
        marginHorizontal: 16,
        borderRadius: 22,
        padding: 18,
        borderWidth: 1,
        shadowColor: '#120B09',
        shadowOffset: { width: 0, height: 10 },
        shadowRadius: 22,
        elevation: 4,
    },
    sectionKicker: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.5,
        marginBottom: 14,
    },
    locationStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    locationStatusText: {
        fontSize: 12,
        fontWeight: '600',
    },
    errorBanner: {
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 12,
    },
    errorText: {
        fontSize: 13,
        fontWeight: '600',
    },
    addressText: {
        fontSize: 20,
        lineHeight: 28,
        fontWeight: '800',
        marginBottom: 12,
    },
    tsText: {
        fontSize: 13,
        lineHeight: 20,
        fontWeight: '500',
    },
    inputLabel: {
        fontSize: 15,
        fontWeight: '700',
        marginBottom: 9,
    },
    titleInput: {
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 18,
    },
    descriptionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 9,
    },
    charCount: {
        fontSize: 12,
        fontWeight: '600',
    },
    descriptionInput: {
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        minHeight: 130,
        fontSize: 15,
        lineHeight: 22,
        marginBottom: 12,
    },
    detailHint: {
        fontSize: 13,
        lineHeight: 19,
    },
    actions: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 16,
        marginTop: 18,
    },
    retakeBtn: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 18,
        alignItems: 'center',
        borderWidth: 1,
    },
    retakeBtnText: {
        fontSize: 15,
        fontWeight: '700',
    },
    saveBtn: {
        flex: 1.25,
        paddingVertical: 16,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#D96C4A',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 18,
        elevation: 5,
    },
    saveBtnDisabled: {
        opacity: 0.72,
    },
    singleActionButton: {
        flex: 1,
    },
    saveBtnText: {
        color: '#FFF',
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.2,
    },
    discardHint: {
        marginTop: 14,
        paddingHorizontal: 24,
        textAlign: 'center',
        fontSize: 13,
        lineHeight: 19,
    },
});

export default styles;
