import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        overflow: 'hidden',
    },
    orbOne: {
        position: 'absolute',
        width: 320,
        height: 320,
        borderRadius: 160,
        top: -80,
        right: -120,
    },
    orbTwo: {
        position: 'absolute',
        width: 280,
        height: 280,
        borderRadius: 140,
        bottom: 40,
        left: -120,
    },
    orbThree: {
        position: 'absolute',
        width: 190,
        height: 190,
        borderRadius: 95,
        top: '38%',
        right: -70,
    },
    landmassOne: {
        position: 'absolute',
        width: 220,
        height: 94,
        borderRadius: 999,
        top: 88,
        right: -30,
        transform: [{ rotate: '-18deg' }],
    },
    landmassTwo: {
        position: 'absolute',
        width: 168,
        height: 74,
        borderRadius: 999,
        top: '52%',
        left: -34,
        transform: [{ rotate: '14deg' }],
    },
    contourOne: {
        position: 'absolute',
        width: 420,
        height: 420,
        borderRadius: 210,
        top: -130,
        left: -140,
        borderWidth: 1,
    },
    contourTwo: {
        position: 'absolute',
        width: 360,
        height: 360,
        borderRadius: 180,
        bottom: -110,
        right: -120,
        borderWidth: 1,
    },
    contourThree: {
        position: 'absolute',
        width: '88%',
        height: 210,
        borderRadius: 999,
        left: '6%',
        top: '32%',
        borderWidth: 1,
        transform: [{ rotate: '-11deg' }],
    },
    contourFour: {
        position: 'absolute',
        width: '92%',
        height: 250,
        borderRadius: 999,
        left: '-8%',
        top: '58%',
        borderWidth: 1,
        transform: [{ rotate: '9deg' }],
    },
    latitudeBand: {
        position: 'absolute',
        width: '140%',
        height: 120,
        left: '-20%',
        top: '24%',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderRadius: 999,
    },
    longitudeBand: {
        position: 'absolute',
        width: 210,
        height: '140%',
        top: '-20%',
        right: 28,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderRadius: 999,
    },
});

export default styles;
